server:
  port: 8080

spring:
  application:
    name: student-score-master
  datasource:
    url: jdbc:mysql://localhost:3306/student-score-db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver